# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'weather.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\"\x07\n\x05\x45mpty\"\x1f\n\rReportRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\"H\n\x0cWeatherStats\x12\x10\n\x08\x61vg_temp\x18\x01 \x01(\x02\x12\x10\n\x08max_temp\x18\x02 \x01(\x02\x12\x14\n\x0ctotal_alerts\x18\x03 \x01(\x05\"B\n\x0c\x41lertMessage\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x0f\n\x07message\x18\x03 \x01(\t\"g\n\rSensorReading\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12\x10\n\x08pressure\x18\x04 \x01(\x02\x12\n\n\x02ts\x18\x05 \x01(\x03\"$\n\tSensorAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t2u\n\x10\x41nalyticsService\x12\x33\n\x10SubscribeToStats\x12\x0e.ReportRequest\x1a\r.WeatherStats0\x01\x12,\n\x11SubscribeToAlerts\x12\x06.Empty\x1a\r.AlertMessage0\x01\x32\x41\n\rSensorService\x12\x30\n\x10StreamSensorData\x12\x0e.SensorReading\x1a\n.SensorAck(\x01\x42\x45\n\x11\x63om.weather.protoB\x0cWeatherProtoP\x01Z github.com/hasan/weather;weatherb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.weather.protoB\014WeatherProtoP\001Z github.com/hasan/weather;weather'
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_REPORTREQUEST']._serialized_start=26
  _globals['_REPORTREQUEST']._serialized_end=57
  _globals['_WEATHERSTATS']._serialized_start=59
  _globals['_WEATHERSTATS']._serialized_end=131
  _globals['_ALERTMESSAGE']._serialized_start=133
  _globals['_ALERTMESSAGE']._serialized_end=199
  _globals['_SENSORREADING']._serialized_start=201
  _globals['_SENSORREADING']._serialized_end=304
  _globals['_SENSORACK']._serialized_start=306
  _globals['_SENSORACK']._serialized_end=342
  _globals['_ANALYTICSSERVICE']._serialized_start=344
  _globals['_ANALYTICSSERVICE']._serialized_end=461
  _globals['_SENSORSERVICE']._serialized_start=463
  _globals['_SENSORSERVICE']._serialized_end=528
# @@protoc_insertion_point(module_scope)
