// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.3
package com.weather.proto;

public interface AlertMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weather.AlertMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor_id = 1;</code>
   * @return The sensorId.
   */
  java.lang.String getSensorId();
  /**
   * <code>string sensor_id = 1;</code>
   * @return The bytes for sensorId.
   */
  com.google.protobuf.ByteString
      getSensorIdBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.weather.AlertMessage.Severity severity = 3;</code>
   * @return The enum numeric value on the wire for severity.
   */
  int getSeverityValue();
  /**
   * <code>.weather.AlertMessage.Severity severity = 3;</code>
   * @return The severity.
   */
  com.weather.proto.AlertMessage.Severity getSeverity();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
