// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.3
package com.weather.proto;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weather.Empty)
    com.google.protobuf.MessageOrBuilder {
}
