// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.3
package com.weather.proto;

public interface ReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string region = 1;</code>
   * @return The region.
   */
  java.lang.String getRegion();
  /**
   * <code>string region = 1;</code>
   * @return The bytes for region.
   */
  com.google.protobuf.ByteString
      getRegionBytes();
}
