// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.3
package com.weather.proto;

/**
 * <pre>
 * Sensor service: client-streaming RPC for sensors to send readings
 * </pre>
 *
 * Protobuf type {@code SensorReading}
 */
public final class SensorReading extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SensorReading)
    SensorReadingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SensorReading.newBuilder() to construct.
  private SensorReading(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SensorReading() {
    sensorId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SensorReading();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.weather.proto.WeatherProto.internal_static_SensorReading_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.weather.proto.WeatherProto.internal_static_SensorReading_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.weather.proto.SensorReading.class, com.weather.proto.SensorReading.Builder.class);
  }

  public static final int SENSOR_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sensorId_ = "";
  /**
   * <code>string sensor_id = 1;</code>
   * @return The sensorId.
   */
  @java.lang.Override
  public java.lang.String getSensorId() {
    java.lang.Object ref = sensorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sensorId_ = s;
      return s;
    }
  }
  /**
   * <code>string sensor_id = 1;</code>
   * @return The bytes for sensorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSensorIdBytes() {
    java.lang.Object ref = sensorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sensorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 2;
  private float temperature_ = 0F;
  /**
   * <code>float temperature = 2;</code>
   * @return The temperature.
   */
  @java.lang.Override
  public float getTemperature() {
    return temperature_;
  }

  public static final int HUMIDITY_FIELD_NUMBER = 3;
  private float humidity_ = 0F;
  /**
   * <code>float humidity = 3;</code>
   * @return The humidity.
   */
  @java.lang.Override
  public float getHumidity() {
    return humidity_;
  }

  public static final int PRESSURE_FIELD_NUMBER = 4;
  private float pressure_ = 0F;
  /**
   * <code>float pressure = 4;</code>
   * @return The pressure.
   */
  @java.lang.Override
  public float getPressure() {
    return pressure_;
  }

  public static final int TS_FIELD_NUMBER = 5;
  private long ts_ = 0L;
  /**
   * <pre>
   * unix epoch ms
   * </pre>
   *
   * <code>int64 ts = 5;</code>
   * @return The ts.
   */
  @java.lang.Override
  public long getTs() {
    return ts_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sensorId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sensorId_);
    }
    if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
      output.writeFloat(2, temperature_);
    }
    if (java.lang.Float.floatToRawIntBits(humidity_) != 0) {
      output.writeFloat(3, humidity_);
    }
    if (java.lang.Float.floatToRawIntBits(pressure_) != 0) {
      output.writeFloat(4, pressure_);
    }
    if (ts_ != 0L) {
      output.writeInt64(5, ts_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sensorId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sensorId_);
    }
    if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, temperature_);
    }
    if (java.lang.Float.floatToRawIntBits(humidity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, humidity_);
    }
    if (java.lang.Float.floatToRawIntBits(pressure_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, pressure_);
    }
    if (ts_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, ts_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.weather.proto.SensorReading)) {
      return super.equals(obj);
    }
    com.weather.proto.SensorReading other = (com.weather.proto.SensorReading) obj;

    if (!getSensorId()
        .equals(other.getSensorId())) return false;
    if (java.lang.Float.floatToIntBits(getTemperature())
        != java.lang.Float.floatToIntBits(
            other.getTemperature())) return false;
    if (java.lang.Float.floatToIntBits(getHumidity())
        != java.lang.Float.floatToIntBits(
            other.getHumidity())) return false;
    if (java.lang.Float.floatToIntBits(getPressure())
        != java.lang.Float.floatToIntBits(
            other.getPressure())) return false;
    if (getTs()
        != other.getTs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENSOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSensorId().hashCode();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTemperature());
    hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getHumidity());
    hash = (37 * hash) + PRESSURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPressure());
    hash = (37 * hash) + TS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.weather.proto.SensorReading parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.weather.proto.SensorReading parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.weather.proto.SensorReading parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.weather.proto.SensorReading parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.weather.proto.SensorReading parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.weather.proto.SensorReading parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.weather.proto.SensorReading parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.weather.proto.SensorReading parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.weather.proto.SensorReading parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.weather.proto.SensorReading parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.weather.proto.SensorReading parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.weather.proto.SensorReading parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.weather.proto.SensorReading prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Sensor service: client-streaming RPC for sensors to send readings
   * </pre>
   *
   * Protobuf type {@code SensorReading}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SensorReading)
      com.weather.proto.SensorReadingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.weather.proto.WeatherProto.internal_static_SensorReading_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.weather.proto.WeatherProto.internal_static_SensorReading_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.weather.proto.SensorReading.class, com.weather.proto.SensorReading.Builder.class);
    }

    // Construct using com.weather.proto.SensorReading.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sensorId_ = "";
      temperature_ = 0F;
      humidity_ = 0F;
      pressure_ = 0F;
      ts_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.weather.proto.WeatherProto.internal_static_SensorReading_descriptor;
    }

    @java.lang.Override
    public com.weather.proto.SensorReading getDefaultInstanceForType() {
      return com.weather.proto.SensorReading.getDefaultInstance();
    }

    @java.lang.Override
    public com.weather.proto.SensorReading build() {
      com.weather.proto.SensorReading result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.weather.proto.SensorReading buildPartial() {
      com.weather.proto.SensorReading result = new com.weather.proto.SensorReading(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.weather.proto.SensorReading result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sensorId_ = sensorId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.temperature_ = temperature_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.humidity_ = humidity_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pressure_ = pressure_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.ts_ = ts_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.weather.proto.SensorReading) {
        return mergeFrom((com.weather.proto.SensorReading)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.weather.proto.SensorReading other) {
      if (other == com.weather.proto.SensorReading.getDefaultInstance()) return this;
      if (!other.getSensorId().isEmpty()) {
        sensorId_ = other.sensorId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTemperature() != 0F) {
        setTemperature(other.getTemperature());
      }
      if (other.getHumidity() != 0F) {
        setHumidity(other.getHumidity());
      }
      if (other.getPressure() != 0F) {
        setPressure(other.getPressure());
      }
      if (other.getTs() != 0L) {
        setTs(other.getTs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sensorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 21: {
              temperature_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              humidity_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 37: {
              pressure_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            case 40: {
              ts_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sensorId_ = "";
    /**
     * <code>string sensor_id = 1;</code>
     * @return The sensorId.
     */
    public java.lang.String getSensorId() {
      java.lang.Object ref = sensorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sensorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sensor_id = 1;</code>
     * @return The bytes for sensorId.
     */
    public com.google.protobuf.ByteString
        getSensorIdBytes() {
      java.lang.Object ref = sensorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sensor_id = 1;</code>
     * @param value The sensorId to set.
     * @return This builder for chaining.
     */
    public Builder setSensorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sensorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sensor_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensorId() {
      sensorId_ = getDefaultInstance().getSensorId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sensor_id = 1;</code>
     * @param value The bytes for sensorId to set.
     * @return This builder for chaining.
     */
    public Builder setSensorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sensorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private float temperature_ ;
    /**
     * <code>float temperature = 2;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public float getTemperature() {
      return temperature_;
    }
    /**
     * <code>float temperature = 2;</code>
     * @param value The temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperature(float value) {

      temperature_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float temperature = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperature() {
      bitField0_ = (bitField0_ & ~0x00000002);
      temperature_ = 0F;
      onChanged();
      return this;
    }

    private float humidity_ ;
    /**
     * <code>float humidity = 3;</code>
     * @return The humidity.
     */
    @java.lang.Override
    public float getHumidity() {
      return humidity_;
    }
    /**
     * <code>float humidity = 3;</code>
     * @param value The humidity to set.
     * @return This builder for chaining.
     */
    public Builder setHumidity(float value) {

      humidity_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float humidity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHumidity() {
      bitField0_ = (bitField0_ & ~0x00000004);
      humidity_ = 0F;
      onChanged();
      return this;
    }

    private float pressure_ ;
    /**
     * <code>float pressure = 4;</code>
     * @return The pressure.
     */
    @java.lang.Override
    public float getPressure() {
      return pressure_;
    }
    /**
     * <code>float pressure = 4;</code>
     * @param value The pressure to set.
     * @return This builder for chaining.
     */
    public Builder setPressure(float value) {

      pressure_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float pressure = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPressure() {
      bitField0_ = (bitField0_ & ~0x00000008);
      pressure_ = 0F;
      onChanged();
      return this;
    }

    private long ts_ ;
    /**
     * <pre>
     * unix epoch ms
     * </pre>
     *
     * <code>int64 ts = 5;</code>
     * @return The ts.
     */
    @java.lang.Override
    public long getTs() {
      return ts_;
    }
    /**
     * <pre>
     * unix epoch ms
     * </pre>
     *
     * <code>int64 ts = 5;</code>
     * @param value The ts to set.
     * @return This builder for chaining.
     */
    public Builder setTs(long value) {

      ts_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unix epoch ms
     * </pre>
     *
     * <code>int64 ts = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      ts_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SensorReading)
  }

  // @@protoc_insertion_point(class_scope:SensorReading)
  private static final com.weather.proto.SensorReading DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.weather.proto.SensorReading();
  }

  public static com.weather.proto.SensorReading getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SensorReading>
      PARSER = new com.google.protobuf.AbstractParser<SensorReading>() {
    @java.lang.Override
    public SensorReading parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SensorReading> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SensorReading> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.weather.proto.SensorReading getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

