// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.3
package com.weather.proto;

public interface SensorReadingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensorReading)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor_id = 1;</code>
   * @return The sensorId.
   */
  java.lang.String getSensorId();
  /**
   * <code>string sensor_id = 1;</code>
   * @return The bytes for sensorId.
   */
  com.google.protobuf.ByteString
      getSensorIdBytes();

  /**
   * <code>float temperature = 2;</code>
   * @return The temperature.
   */
  float getTemperature();

  /**
   * <code>float humidity = 3;</code>
   * @return The humidity.
   */
  float getHumidity();

  /**
   * <code>float pressure = 4;</code>
   * @return The pressure.
   */
  float getPressure();

  /**
   * <pre>
   * unix epoch ms
   * </pre>
   *
   * <code>int64 ts = 5;</code>
   * @return The ts.
   */
  long getTs();
}
