// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.3
package com.weather.proto;

public interface WeatherDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weather.WeatherData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor_id = 1;</code>
   * @return The sensorId.
   */
  java.lang.String getSensorId();
  /**
   * <code>string sensor_id = 1;</code>
   * @return The bytes for sensorId.
   */
  com.google.protobuf.ByteString
      getSensorIdBytes();

  /**
   * <code>double temperature = 2;</code>
   * @return The temperature.
   */
  double getTemperature();

  /**
   * <code>double humidity = 3;</code>
   * @return The humidity.
   */
  double getHumidity();

  /**
   * <code>double pressure = 4;</code>
   * @return The pressure.
   */
  double getPressure();

  /**
   * <code>int64 timestamp = 5;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
