// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.3
package com.weather.proto;

public interface WeatherStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WeatherStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float avg_temp = 1;</code>
   * @return The avgTemp.
   */
  float getAvgTemp();

  /**
   * <code>float max_temp = 2;</code>
   * @return The maxTemp.
   */
  float getMaxTemp();

  /**
   * <code>int32 total_alerts = 3;</code>
   * @return The totalAlerts.
   */
  int getTotalAlerts();
}
