// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.3
package com.weather.proto;

/**
 * Protobuf type {@code WeatherStats}
 */
public final class WeatherStats extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WeatherStats)
    WeatherStatsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeatherStats.newBuilder() to construct.
  private WeatherStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeatherStats() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WeatherStats();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.weather.proto.WeatherProto.internal_static_WeatherStats_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.weather.proto.WeatherProto.internal_static_WeatherStats_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.weather.proto.WeatherStats.class, com.weather.proto.WeatherStats.Builder.class);
  }

  public static final int AVG_TEMP_FIELD_NUMBER = 1;
  private float avgTemp_ = 0F;
  /**
   * <code>float avg_temp = 1;</code>
   * @return The avgTemp.
   */
  @java.lang.Override
  public float getAvgTemp() {
    return avgTemp_;
  }

  public static final int MAX_TEMP_FIELD_NUMBER = 2;
  private float maxTemp_ = 0F;
  /**
   * <code>float max_temp = 2;</code>
   * @return The maxTemp.
   */
  @java.lang.Override
  public float getMaxTemp() {
    return maxTemp_;
  }

  public static final int TOTAL_ALERTS_FIELD_NUMBER = 3;
  private int totalAlerts_ = 0;
  /**
   * <code>int32 total_alerts = 3;</code>
   * @return The totalAlerts.
   */
  @java.lang.Override
  public int getTotalAlerts() {
    return totalAlerts_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(avgTemp_) != 0) {
      output.writeFloat(1, avgTemp_);
    }
    if (java.lang.Float.floatToRawIntBits(maxTemp_) != 0) {
      output.writeFloat(2, maxTemp_);
    }
    if (totalAlerts_ != 0) {
      output.writeInt32(3, totalAlerts_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Float.floatToRawIntBits(avgTemp_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, avgTemp_);
    }
    if (java.lang.Float.floatToRawIntBits(maxTemp_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, maxTemp_);
    }
    if (totalAlerts_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalAlerts_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.weather.proto.WeatherStats)) {
      return super.equals(obj);
    }
    com.weather.proto.WeatherStats other = (com.weather.proto.WeatherStats) obj;

    if (java.lang.Float.floatToIntBits(getAvgTemp())
        != java.lang.Float.floatToIntBits(
            other.getAvgTemp())) return false;
    if (java.lang.Float.floatToIntBits(getMaxTemp())
        != java.lang.Float.floatToIntBits(
            other.getMaxTemp())) return false;
    if (getTotalAlerts()
        != other.getTotalAlerts()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AVG_TEMP_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAvgTemp());
    hash = (37 * hash) + MAX_TEMP_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMaxTemp());
    hash = (37 * hash) + TOTAL_ALERTS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalAlerts();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.weather.proto.WeatherStats parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.weather.proto.WeatherStats parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.weather.proto.WeatherStats parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.weather.proto.WeatherStats parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.weather.proto.WeatherStats parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.weather.proto.WeatherStats prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WeatherStats}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WeatherStats)
      com.weather.proto.WeatherStatsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.weather.proto.WeatherProto.internal_static_WeatherStats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.weather.proto.WeatherProto.internal_static_WeatherStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.weather.proto.WeatherStats.class, com.weather.proto.WeatherStats.Builder.class);
    }

    // Construct using com.weather.proto.WeatherStats.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      avgTemp_ = 0F;
      maxTemp_ = 0F;
      totalAlerts_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.weather.proto.WeatherProto.internal_static_WeatherStats_descriptor;
    }

    @java.lang.Override
    public com.weather.proto.WeatherStats getDefaultInstanceForType() {
      return com.weather.proto.WeatherStats.getDefaultInstance();
    }

    @java.lang.Override
    public com.weather.proto.WeatherStats build() {
      com.weather.proto.WeatherStats result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.weather.proto.WeatherStats buildPartial() {
      com.weather.proto.WeatherStats result = new com.weather.proto.WeatherStats(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.weather.proto.WeatherStats result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.avgTemp_ = avgTemp_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.maxTemp_ = maxTemp_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalAlerts_ = totalAlerts_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.weather.proto.WeatherStats) {
        return mergeFrom((com.weather.proto.WeatherStats)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.weather.proto.WeatherStats other) {
      if (other == com.weather.proto.WeatherStats.getDefaultInstance()) return this;
      if (other.getAvgTemp() != 0F) {
        setAvgTemp(other.getAvgTemp());
      }
      if (other.getMaxTemp() != 0F) {
        setMaxTemp(other.getMaxTemp());
      }
      if (other.getTotalAlerts() != 0) {
        setTotalAlerts(other.getTotalAlerts());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              avgTemp_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 21: {
              maxTemp_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 24: {
              totalAlerts_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float avgTemp_ ;
    /**
     * <code>float avg_temp = 1;</code>
     * @return The avgTemp.
     */
    @java.lang.Override
    public float getAvgTemp() {
      return avgTemp_;
    }
    /**
     * <code>float avg_temp = 1;</code>
     * @param value The avgTemp to set.
     * @return This builder for chaining.
     */
    public Builder setAvgTemp(float value) {

      avgTemp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>float avg_temp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgTemp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      avgTemp_ = 0F;
      onChanged();
      return this;
    }

    private float maxTemp_ ;
    /**
     * <code>float max_temp = 2;</code>
     * @return The maxTemp.
     */
    @java.lang.Override
    public float getMaxTemp() {
      return maxTemp_;
    }
    /**
     * <code>float max_temp = 2;</code>
     * @param value The maxTemp to set.
     * @return This builder for chaining.
     */
    public Builder setMaxTemp(float value) {

      maxTemp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float max_temp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxTemp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      maxTemp_ = 0F;
      onChanged();
      return this;
    }

    private int totalAlerts_ ;
    /**
     * <code>int32 total_alerts = 3;</code>
     * @return The totalAlerts.
     */
    @java.lang.Override
    public int getTotalAlerts() {
      return totalAlerts_;
    }
    /**
     * <code>int32 total_alerts = 3;</code>
     * @param value The totalAlerts to set.
     * @return This builder for chaining.
     */
    public Builder setTotalAlerts(int value) {

      totalAlerts_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_alerts = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalAlerts() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalAlerts_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WeatherStats)
  }

  // @@protoc_insertion_point(class_scope:WeatherStats)
  private static final com.weather.proto.WeatherStats DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.weather.proto.WeatherStats();
  }

  public static com.weather.proto.WeatherStats getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeatherStats>
      PARSER = new com.google.protobuf.AbstractParser<WeatherStats>() {
    @java.lang.Override
    public WeatherStats parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WeatherStats> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeatherStats> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.weather.proto.WeatherStats getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

