// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.3
package com.weather.proto;

public interface WeatherStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weather.WeatherStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor_id = 1;</code>
   * @return The sensorId.
   */
  java.lang.String getSensorId();
  /**
   * <code>string sensor_id = 1;</code>
   * @return The bytes for sensorId.
   */
  com.google.protobuf.ByteString
      getSensorIdBytes();

  /**
   * <code>double avg_temperature = 2;</code>
   * @return The avgTemperature.
   */
  double getAvgTemperature();

  /**
   * <code>double avg_humidity = 3;</code>
   * @return The avgHumidity.
   */
  double getAvgHumidity();

  /**
   * <code>double avg_pressure = 4;</code>
   * @return The avgPressure.
   */
  double getAvgPressure();

  /**
   * <code>int32 sample_count = 5;</code>
   * @return The sampleCount.
   */
  int getSampleCount();

  /**
   * <code>int64 last_update = 6;</code>
   * @return The lastUpdate.
   */
  long getLastUpdate();
}
