// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.3
package com.weather.proto;

public final class WeatherProto {
  private WeatherProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weather_WeatherData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weather_WeatherData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weather_WeatherStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weather_WeatherStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weather_AlertMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weather_AlertMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weather_ReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weather_ReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weather_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weather_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rweather.proto\022\007weather\"l\n\013WeatherData\022" +
      "\021\n\tsensor_id\030\001 \001(\t\022\023\n\013temperature\030\002 \001(\001\022" +
      "\020\n\010humidity\030\003 \001(\001\022\020\n\010pressure\030\004 \001(\001\022\021\n\tt" +
      "imestamp\030\005 \001(\003\"\221\001\n\014WeatherStats\022\021\n\tsenso" +
      "r_id\030\001 \001(\t\022\027\n\017avg_temperature\030\002 \001(\001\022\024\n\014a" +
      "vg_humidity\030\003 \001(\001\022\024\n\014avg_pressure\030\004 \001(\001\022" +
      "\024\n\014sample_count\030\005 \001(\005\022\023\n\013last_update\030\006 \001" +
      "(\003\"\250\001\n\014AlertMessage\022\021\n\tsensor_id\030\001 \001(\t\022\017" +
      "\n\007message\030\002 \001(\t\0220\n\010severity\030\003 \001(\0162\036.weat" +
      "her.AlertMessage.Severity\022\021\n\ttimestamp\030\004" +
      " \001(\003\"/\n\010Severity\022\010\n\004INFO\020\000\022\013\n\007WARNING\020\001\022" +
      "\014\n\010CRITICAL\020\002\"\"\n\rReportRequest\022\021\n\tsensor" +
      "_id\030\001 \001(\t\"\007\n\005Empty2S\n\024WeatherSensorServi" +
      "ce\022;\n\021StreamWeatherData\022\024.weather.Weathe" +
      "rData\032\016.weather.Empty(\0012\225\001\n\020AnalyticsSer" +
      "vice\022C\n\020SubscribeToStats\022\026.weather.Repor" +
      "tRequest\032\025.weather.WeatherStats0\001\022<\n\021Sub" +
      "scribeToAlerts\022\016.weather.Empty\032\025.weather" +
      ".AlertMessage0\0012U\n\020DashboardService\022A\n\020G" +
      "etCurrentReport\022\026.weather.ReportRequest\032" +
      "\025.weather.WeatherStatsB#\n\021com.weather.pr" +
      "otoB\014WeatherProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_weather_WeatherData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_weather_WeatherData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weather_WeatherData_descriptor,
        new java.lang.String[] { "SensorId", "Temperature", "Humidity", "Pressure", "Timestamp", });
    internal_static_weather_WeatherStats_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_weather_WeatherStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weather_WeatherStats_descriptor,
        new java.lang.String[] { "SensorId", "AvgTemperature", "AvgHumidity", "AvgPressure", "SampleCount", "LastUpdate", });
    internal_static_weather_AlertMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_weather_AlertMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weather_AlertMessage_descriptor,
        new java.lang.String[] { "SensorId", "Message", "Severity", "Timestamp", });
    internal_static_weather_ReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_weather_ReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weather_ReportRequest_descriptor,
        new java.lang.String[] { "SensorId", });
    internal_static_weather_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_weather_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weather_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
