// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.3
package com.weather.proto;

/**
 * Protobuf type {@code weather.WeatherStats}
 */
public final class WeatherStats extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:weather.WeatherStats)
    WeatherStatsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeatherStats.newBuilder() to construct.
  private WeatherStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeatherStats() {
    sensorId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WeatherStats();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.weather.proto.WeatherProto.internal_static_weather_WeatherStats_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.weather.proto.WeatherProto.internal_static_weather_WeatherStats_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.weather.proto.WeatherStats.class, com.weather.proto.WeatherStats.Builder.class);
  }

  public static final int SENSOR_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sensorId_ = "";
  /**
   * <code>string sensor_id = 1;</code>
   * @return The sensorId.
   */
  @java.lang.Override
  public java.lang.String getSensorId() {
    java.lang.Object ref = sensorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sensorId_ = s;
      return s;
    }
  }
  /**
   * <code>string sensor_id = 1;</code>
   * @return The bytes for sensorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSensorIdBytes() {
    java.lang.Object ref = sensorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sensorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVG_TEMPERATURE_FIELD_NUMBER = 2;
  private double avgTemperature_ = 0D;
  /**
   * <code>double avg_temperature = 2;</code>
   * @return The avgTemperature.
   */
  @java.lang.Override
  public double getAvgTemperature() {
    return avgTemperature_;
  }

  public static final int AVG_HUMIDITY_FIELD_NUMBER = 3;
  private double avgHumidity_ = 0D;
  /**
   * <code>double avg_humidity = 3;</code>
   * @return The avgHumidity.
   */
  @java.lang.Override
  public double getAvgHumidity() {
    return avgHumidity_;
  }

  public static final int AVG_PRESSURE_FIELD_NUMBER = 4;
  private double avgPressure_ = 0D;
  /**
   * <code>double avg_pressure = 4;</code>
   * @return The avgPressure.
   */
  @java.lang.Override
  public double getAvgPressure() {
    return avgPressure_;
  }

  public static final int SAMPLE_COUNT_FIELD_NUMBER = 5;
  private int sampleCount_ = 0;
  /**
   * <code>int32 sample_count = 5;</code>
   * @return The sampleCount.
   */
  @java.lang.Override
  public int getSampleCount() {
    return sampleCount_;
  }

  public static final int LAST_UPDATE_FIELD_NUMBER = 6;
  private long lastUpdate_ = 0L;
  /**
   * <code>int64 last_update = 6;</code>
   * @return The lastUpdate.
   */
  @java.lang.Override
  public long getLastUpdate() {
    return lastUpdate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sensorId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sensorId_);
    }
    if (java.lang.Double.doubleToRawLongBits(avgTemperature_) != 0) {
      output.writeDouble(2, avgTemperature_);
    }
    if (java.lang.Double.doubleToRawLongBits(avgHumidity_) != 0) {
      output.writeDouble(3, avgHumidity_);
    }
    if (java.lang.Double.doubleToRawLongBits(avgPressure_) != 0) {
      output.writeDouble(4, avgPressure_);
    }
    if (sampleCount_ != 0) {
      output.writeInt32(5, sampleCount_);
    }
    if (lastUpdate_ != 0L) {
      output.writeInt64(6, lastUpdate_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sensorId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sensorId_);
    }
    if (java.lang.Double.doubleToRawLongBits(avgTemperature_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, avgTemperature_);
    }
    if (java.lang.Double.doubleToRawLongBits(avgHumidity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, avgHumidity_);
    }
    if (java.lang.Double.doubleToRawLongBits(avgPressure_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, avgPressure_);
    }
    if (sampleCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, sampleCount_);
    }
    if (lastUpdate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, lastUpdate_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.weather.proto.WeatherStats)) {
      return super.equals(obj);
    }
    com.weather.proto.WeatherStats other = (com.weather.proto.WeatherStats) obj;

    if (!getSensorId()
        .equals(other.getSensorId())) return false;
    if (java.lang.Double.doubleToLongBits(getAvgTemperature())
        != java.lang.Double.doubleToLongBits(
            other.getAvgTemperature())) return false;
    if (java.lang.Double.doubleToLongBits(getAvgHumidity())
        != java.lang.Double.doubleToLongBits(
            other.getAvgHumidity())) return false;
    if (java.lang.Double.doubleToLongBits(getAvgPressure())
        != java.lang.Double.doubleToLongBits(
            other.getAvgPressure())) return false;
    if (getSampleCount()
        != other.getSampleCount()) return false;
    if (getLastUpdate()
        != other.getLastUpdate()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENSOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSensorId().hashCode();
    hash = (37 * hash) + AVG_TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAvgTemperature()));
    hash = (37 * hash) + AVG_HUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAvgHumidity()));
    hash = (37 * hash) + AVG_PRESSURE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAvgPressure()));
    hash = (37 * hash) + SAMPLE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getSampleCount();
    hash = (37 * hash) + LAST_UPDATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastUpdate());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.weather.proto.WeatherStats parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.weather.proto.WeatherStats parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.weather.proto.WeatherStats parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.weather.proto.WeatherStats parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.weather.proto.WeatherStats parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.weather.proto.WeatherStats parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.weather.proto.WeatherStats prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code weather.WeatherStats}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:weather.WeatherStats)
      com.weather.proto.WeatherStatsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.weather.proto.WeatherProto.internal_static_weather_WeatherStats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.weather.proto.WeatherProto.internal_static_weather_WeatherStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.weather.proto.WeatherStats.class, com.weather.proto.WeatherStats.Builder.class);
    }

    // Construct using com.weather.proto.WeatherStats.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sensorId_ = "";
      avgTemperature_ = 0D;
      avgHumidity_ = 0D;
      avgPressure_ = 0D;
      sampleCount_ = 0;
      lastUpdate_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.weather.proto.WeatherProto.internal_static_weather_WeatherStats_descriptor;
    }

    @java.lang.Override
    public com.weather.proto.WeatherStats getDefaultInstanceForType() {
      return com.weather.proto.WeatherStats.getDefaultInstance();
    }

    @java.lang.Override
    public com.weather.proto.WeatherStats build() {
      com.weather.proto.WeatherStats result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.weather.proto.WeatherStats buildPartial() {
      com.weather.proto.WeatherStats result = new com.weather.proto.WeatherStats(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.weather.proto.WeatherStats result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sensorId_ = sensorId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.avgTemperature_ = avgTemperature_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.avgHumidity_ = avgHumidity_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.avgPressure_ = avgPressure_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sampleCount_ = sampleCount_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.lastUpdate_ = lastUpdate_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.weather.proto.WeatherStats) {
        return mergeFrom((com.weather.proto.WeatherStats)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.weather.proto.WeatherStats other) {
      if (other == com.weather.proto.WeatherStats.getDefaultInstance()) return this;
      if (!other.getSensorId().isEmpty()) {
        sensorId_ = other.sensorId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAvgTemperature() != 0D) {
        setAvgTemperature(other.getAvgTemperature());
      }
      if (other.getAvgHumidity() != 0D) {
        setAvgHumidity(other.getAvgHumidity());
      }
      if (other.getAvgPressure() != 0D) {
        setAvgPressure(other.getAvgPressure());
      }
      if (other.getSampleCount() != 0) {
        setSampleCount(other.getSampleCount());
      }
      if (other.getLastUpdate() != 0L) {
        setLastUpdate(other.getLastUpdate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sensorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              avgTemperature_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              avgHumidity_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              avgPressure_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 40: {
              sampleCount_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              lastUpdate_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sensorId_ = "";
    /**
     * <code>string sensor_id = 1;</code>
     * @return The sensorId.
     */
    public java.lang.String getSensorId() {
      java.lang.Object ref = sensorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sensorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sensor_id = 1;</code>
     * @return The bytes for sensorId.
     */
    public com.google.protobuf.ByteString
        getSensorIdBytes() {
      java.lang.Object ref = sensorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sensor_id = 1;</code>
     * @param value The sensorId to set.
     * @return This builder for chaining.
     */
    public Builder setSensorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sensorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sensor_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensorId() {
      sensorId_ = getDefaultInstance().getSensorId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sensor_id = 1;</code>
     * @param value The bytes for sensorId to set.
     * @return This builder for chaining.
     */
    public Builder setSensorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sensorId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double avgTemperature_ ;
    /**
     * <code>double avg_temperature = 2;</code>
     * @return The avgTemperature.
     */
    @java.lang.Override
    public double getAvgTemperature() {
      return avgTemperature_;
    }
    /**
     * <code>double avg_temperature = 2;</code>
     * @param value The avgTemperature to set.
     * @return This builder for chaining.
     */
    public Builder setAvgTemperature(double value) {

      avgTemperature_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double avg_temperature = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgTemperature() {
      bitField0_ = (bitField0_ & ~0x00000002);
      avgTemperature_ = 0D;
      onChanged();
      return this;
    }

    private double avgHumidity_ ;
    /**
     * <code>double avg_humidity = 3;</code>
     * @return The avgHumidity.
     */
    @java.lang.Override
    public double getAvgHumidity() {
      return avgHumidity_;
    }
    /**
     * <code>double avg_humidity = 3;</code>
     * @param value The avgHumidity to set.
     * @return This builder for chaining.
     */
    public Builder setAvgHumidity(double value) {

      avgHumidity_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double avg_humidity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgHumidity() {
      bitField0_ = (bitField0_ & ~0x00000004);
      avgHumidity_ = 0D;
      onChanged();
      return this;
    }

    private double avgPressure_ ;
    /**
     * <code>double avg_pressure = 4;</code>
     * @return The avgPressure.
     */
    @java.lang.Override
    public double getAvgPressure() {
      return avgPressure_;
    }
    /**
     * <code>double avg_pressure = 4;</code>
     * @param value The avgPressure to set.
     * @return This builder for chaining.
     */
    public Builder setAvgPressure(double value) {

      avgPressure_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double avg_pressure = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgPressure() {
      bitField0_ = (bitField0_ & ~0x00000008);
      avgPressure_ = 0D;
      onChanged();
      return this;
    }

    private int sampleCount_ ;
    /**
     * <code>int32 sample_count = 5;</code>
     * @return The sampleCount.
     */
    @java.lang.Override
    public int getSampleCount() {
      return sampleCount_;
    }
    /**
     * <code>int32 sample_count = 5;</code>
     * @param value The sampleCount to set.
     * @return This builder for chaining.
     */
    public Builder setSampleCount(int value) {

      sampleCount_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sample_count = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleCount() {
      bitField0_ = (bitField0_ & ~0x00000010);
      sampleCount_ = 0;
      onChanged();
      return this;
    }

    private long lastUpdate_ ;
    /**
     * <code>int64 last_update = 6;</code>
     * @return The lastUpdate.
     */
    @java.lang.Override
    public long getLastUpdate() {
      return lastUpdate_;
    }
    /**
     * <code>int64 last_update = 6;</code>
     * @param value The lastUpdate to set.
     * @return This builder for chaining.
     */
    public Builder setLastUpdate(long value) {

      lastUpdate_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_update = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastUpdate() {
      bitField0_ = (bitField0_ & ~0x00000020);
      lastUpdate_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:weather.WeatherStats)
  }

  // @@protoc_insertion_point(class_scope:weather.WeatherStats)
  private static final com.weather.proto.WeatherStats DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.weather.proto.WeatherStats();
  }

  public static com.weather.proto.WeatherStats getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeatherStats>
      PARSER = new com.google.protobuf.AbstractParser<WeatherStats>() {
    @java.lang.Override
    public WeatherStats parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WeatherStats> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeatherStats> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.weather.proto.WeatherStats getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

