// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.3
package com.weather.proto;

public final class WeatherProto {
  private WeatherProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WeatherStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WeatherStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AlertMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AlertMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SensorReading_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SensorReading_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SensorAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SensorAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rweather.proto\"\007\n\005Empty\"\037\n\rReportReques" +
      "t\022\016\n\006region\030\001 \001(\t\"H\n\014WeatherStats\022\020\n\010avg" +
      "_temp\030\001 \001(\002\022\020\n\010max_temp\030\002 \001(\002\022\024\n\014total_a" +
      "lerts\030\003 \001(\005\"B\n\014AlertMessage\022\014\n\004city\030\001 \001(" +
      "\t\022\023\n\013temperature\030\002 \001(\002\022\017\n\007message\030\003 \001(\t\"" +
      "g\n\rSensorReading\022\021\n\tsensor_id\030\001 \001(\t\022\023\n\013t" +
      "emperature\030\002 \001(\002\022\020\n\010humidity\030\003 \001(\002\022\020\n\010pr" +
      "essure\030\004 \001(\002\022\n\n\002ts\030\005 \001(\003\"$\n\tSensorAck\022\n\n" +
      "\002ok\030\001 \001(\010\022\013\n\003msg\030\002 \001(\t2u\n\020AnalyticsServi" +
      "ce\0223\n\020SubscribeToStats\022\016.ReportRequest\032\r" +
      ".WeatherStats0\001\022,\n\021SubscribeToAlerts\022\006.E" +
      "mpty\032\r.AlertMessage0\0012A\n\rSensorService\0220" +
      "\n\020StreamSensorData\022\016.SensorReading\032\n.Sen" +
      "sorAck(\001BE\n\021com.weather.protoB\014WeatherPr" +
      "otoP\001Z github.com/hasan/weather;weatherb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_ReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReportRequest_descriptor,
        new java.lang.String[] { "Region", });
    internal_static_WeatherStats_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WeatherStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WeatherStats_descriptor,
        new java.lang.String[] { "AvgTemp", "MaxTemp", "TotalAlerts", });
    internal_static_AlertMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AlertMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AlertMessage_descriptor,
        new java.lang.String[] { "City", "Temperature", "Message", });
    internal_static_SensorReading_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SensorReading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SensorReading_descriptor,
        new java.lang.String[] { "SensorId", "Temperature", "Humidity", "Pressure", "Ts", });
    internal_static_SensorAck_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SensorAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SensorAck_descriptor,
        new java.lang.String[] { "Ok", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
